console.log('Hello World, this is not my first npm package')
console.log('Second version')
console.log('Third version, if this gets released than semantic-release is smart')
console.log('Oh so semantic release analyzes commit title... cool')
console.log('dont forget that --access-public is mandatory')
console.log('lets see now it works or not')